version: '3.3'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer.containerfile
    volumes:
      - ../:/workspace
    env_file:
      - .env 

  backdrop:
    build:
      context: ./
      dockerfile: backdrop.containerfile
    container_name: backdrop
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    links:
      - backdrop
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
      - "8411:8411"
    volumes:
      - ../:/workspace
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mariadb:11
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - .env