version: '3.3'

services:
  devcontainer:
    build:
      context: ./
      dockerfile: devcontainer/devcontainer.containerfile
    volumes:
      - ../:/workspace
    env_file:
      - .env 

  drupal9:
    build:
      context: ./
      dockerfile: drupal9/drupal9.containerfile
    container_name: drupal9
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - .env

  drupal10:
    build:
      context: ./
      dockerfile: drupal10/drupal10.containerfile
    container_name: drupal10
    links:
      - db
    volumes:
      - ../:/workspace
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    links:
      - drupal10
      - drupal9
    ports:
      - "80:80"
      - "8009:8009"
      - "8010:8010"
      - "8411:8411"
    volumes:
      - ../:/workspace
      - ./nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mariadb:11
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    env_file:
      - .env